development:
  adapter: postgresql
  encoding: utf8
  database: e_commerce_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: e_commerce_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: e_commerce_production
  pool: 5
  username: 
  password:
    